#include <iostream>
#include "Commands/SetWheelOffsets.h"
#include "Subsystems/Drive/DriveInfo.h"
#include <frc/DriverStation.h>
#include "Util/BSPrefs.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

SetWheelOffsets::SetWheelOffsets(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    SetRunWhenDisabled(true);
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void SetWheelOffsets::Initialize() {
	if (frc::DriverStation::GetInstance().IsDisabled()) {
		std::cout << "Start Offsets\n";
		DriveInfo<double> offsets = Robot::driveBase->CalculatePositionOffsets();
		auto prefs = BSPrefs::GetInstance();
		prefs->StoreDouble("FLOff", offsets.FL);
		prefs->StoreDouble("FROff", offsets.FR);
		prefs->StoreDouble("RLOff", offsets.RL);
		prefs->StoreDouble("RROff", offsets.RR);
		prefs->SaveConstants();
		Robot::driveBase->ZeroTurnInfo();
		SetTimeout(1);
		std::cout << "Completed SetWheelOffsets::Initialize\n";
	} else {
		SetTimeout(0);
	}


}

// Called repeatedly when this Command is scheduled to run
void SetWheelOffsets::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool SetWheelOffsets::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void SetWheelOffsets::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetWheelOffsets::Interrupted() {

}
