#include <iostream>
#include <ctre/Phoenix.h>
#include "Commands/ZeroFeederArmHigh.h"
#include "Robot.h"
#include "Util/BSPrefs.h"



// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ZeroFeederArmHigh::ZeroFeederArmHigh(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    SetRunWhenDisabled(true);
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ZeroFeederArmHigh::Initialize() {
	std::cout << "****** ZERO FEEDER ARM HIGH ******\n";
    int position = BSPrefs::GetInstance()->GetDouble("FeederArm.Pos.Vertical", -108000);
	Robot::feederArm->ZeroArmPosition(position);
	std::cout << "****** ZERO FEEDER ARM HIGH ******\n";
	SetTimeout(1);
}

// Called repeatedly when this Command is scheduled to run
void ZeroFeederArmHigh::Execute() {

}
// Make this return true when this Command no longer needs to run execute()
bool ZeroFeederArmHigh::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void ZeroFeederArmHigh::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ZeroFeederArmHigh::Interrupted() {

}
